#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Ddatabase=simple \
    -Dgtk=disabled \
    -Dx11=disabled \
    -Ddoxygen=false \
    -Dtests=false \
    -Dman=false \
    . output

ninja -C output
ninja -C output install
