#!/bin/sh -e

install -d "$1/opt/discord"
cp -a . "$1/opt/discord"

for file in discord.desktop postinst.sh; do
    rm "$1/opt/discord/$file"
done

chmod 755 "$1/opt/discord/Discord"

# setuid on chrome-sandbox
chmod u+s "$1/opt/discord/chrome-sandbox"

install -d "$1/usr/bin"
ln -s "/opt/discord/Discord" "$1/usr/bin/discord"
